substitutions:
  _IMAGE_FAMILY: "atd-packer-ubuntu-base"
  _SOURCE_IMAGE_FAMILY: "ubuntu-2004-lts"
  _SOURCE_IMAGE_PROJECT: "ubuntu-os-cloud"
  _NETWORK: "default"
  _SUBNETWORK: "default"
  _ZONE: "europe-west1-b"
timeout: 1800s
steps:
  - name: gcr.io/$PROJECT_ID/ansible-packer
    entrypoint: sh
    args:
      - -ce
      - |
        packer init packer/config.pkr.hcl
        packer build \
          packer/template-ubuntu-base.pkr.hcl
    env:
      - "PROJECT_ID=${PROJECT_ID}"
      - "IMAGE_FAMILY=${_IMAGE_FAMILY}"
      - "SOURCE_IMAGE_FAMILY=${_SOURCE_IMAGE_FAMILY}"
      - "SOURCE_IMAGE_PROJECT=${_SOURCE_IMAGE_PROJECT}"
      - "NETWORK=${_NETWORK}"
      - "SUBNETWORK=${_SUBNETWORK}"
      - "ZONE=${_ZONE}"
